OrderManager/OrderManager/Components/BuildingFilterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OrderManager.DataAccess.Repositories.Interfaces;
using OrderManager.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OrderManager.Components
{
    public class BuildingFilterViewComponent : ViewComponent
    {
        private IBuildingRepository _buildingRepository;
        private IUserRepository _userRepository;

        public BuildingFilterViewComponent(IBuildingRepository buildingRepository,
            IUserRepository userRepository)
        {
            _buildingRepository = buildingRepository;
            _userRepository = userRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.BuildingList = await _buildingRepository.GetAllBuildingsAsync();
            List<UserViewModel> userList = new List<UserViewModel>();
            var users = await _userRepository.GetAllUsersAsync();
            foreach (var item in users)
            {
                userList.Add(new UserViewModel() { Id = item.Id, FullName = item.FirstName + " " + item.LastName });
            }
            ViewBag.UserList = userList;
            return View();
        }
    }
}

OrderManager/OrderManager/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OrderManager.DataAccess.Models;
using OrderManager.DataAccess.Repositories.Interfaces;
using OrderManager.ViewModels;

namespace OrderManager.Controllers
{
    [Route("[controller]/[action]")]
    public class AdminOrdersController : Controller
    {
        private IOrderRepository _orderRepository;
        private IMapper _mapper;

        public AdminOrdersController(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }
        public async Task<IActionResult> NewOrders()
        {
            var orderList = await _orderRepository.GetAllNewOrdersAsync();
            ViewBag.Orders = GetOrderList(orderList);
            return View();
        }
        public async Task<IActionResult> OrdersInProgress()
        {
            var orderList = await _orderRepository.GetAllInProgressOrdersAsync();
            ViewBag.Orders = GetOrderList(orderList);
            return View();
        }
        public async Task<IActionResult> EndedOrders()
        {
            var orderList = await _orderRepository.GetAllEndedOrdersAsync();
            ViewBag.Orders = GetOrderList(orderList);
            return View();
        }
        private List<OrderMainViewModel> GetOrderList(IEnumerable<Order> orders)
        {
            var returnList = new List<OrderMainViewModel>();
            foreach (var item in orders)
            {
                var orderItem = new OrderMainViewModel();
                orderItem.BuildingName = item.Building.Name;
                orderItem.OrderName = item.Item;
                returnList.Add(orderItem);
            }
            return returnList;
        }
    }
}

OrderManager/OrderManager/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OrderManager.DataAccess.Models;
using OrderManager.DataAccess.Repositories.Interfaces;
using OrderManager.ViewModels;

namespace OrderManager.Controllers
{
    [Route("[controller]/[action]")]
    public class UserController : Controller
    {
        private IMapper _mapper;
        private IUserRepository _userRepository;

        public UserController(IUserRepository userRepository, IMapper mapper)
        {
            _mapper = mapper;
            _userRepository = userRepository;
        }

        public async Task<ViewResult> Index()
        {
            var users = await _userRepository.GetAllUsersAsync();
            List<UserViewModel> userList = new List<UserViewModel>();
            foreach (var item in users)
            {
                userList.Add(new UserViewModel() { Id = item.Id, FullName = item.FirstName + " " + item.LastName });
            }
            return View(userList);
        }

        public async Task<IActionResult> AddNewUser(UserDetailsViewModel user)
        {
            IdentityResult result = new IdentityResult();
            if (checkIfObjectIsEmpty(user))
            {
                ModelState.Clear();
                return View(nameof(AddNewUser),new UserDetailsViewModel());
            }
            if (ModelState.IsValid && user.Id == null)
            {
                var validatePasswordResult = await _userRepository.ValidatePassword(user.Password);
                if (validatePasswordResult.Succeeded)
                {
                    result = await _userRepository.AddUser(
                        _mapper.Map<UserDetailsViewModel, User>(user), user.Password);
                    return RedirectToAction(nameof(Index));
                } else
                {
                    ModelState.AddModelError("PasswordError",
                        "Hasło musi zawierać małe oraz duże litery, minimum 8 znaków " +
                        "oraz jeden znak niealfanumeryczny");
                }
            }
            else
            {
                ModelState.Remove("Password");
                ModelState.Remove("ConfirmPassword");
                if (ModelState.IsValid && user.Id != null)
                {
                    result = await _userRepository.UpdateUser(_mapper.Map<UserDetailsViewModel, User>(user));
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(user);
        }
        public IActionResult RedirectToChangePassword(UserViewModel user)
        {
           return RedirectToAction(nameof(ChangePassword), new ChangePasswordViewModel() {
               UserId = user.Id});
        }
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var validatePasswordResult = await _userRepository.ValidatePassword(model.Password);
                if (validatePasswordResult.Succeeded)
                {
                    var result = await _userRepository.UpdateUser(
                    model.UserId, model.Password);
                    return RedirectToAction(nameof(Index));
                } else
                {
                    ModelState.AddModelError("PasswordError",
                        "Hasło musi zawierać małe oraz duże litery, minimum 8 znaków oraz jeden znak niealfanumeryczny");
                }
            }
            return View(model);
        }
        public async Task<ViewResult> EditUser(UserViewModel user)
        {
            var userFromDatabase = await _userRepository.GetUserByIdAsync(user.Id);
            UserDetailsViewModel userDetails = new UserDetailsViewModel();
            userDetails = _mapper.Map<User,UserDetailsViewModel>(userFromDatabase);
            return View("AddNewUser", userDetails);
        }
        private bool checkIfObjectIsEmpty(UserDetailsViewModel userModel)
        {
            return userModel.GetType().GetProperties()
                 .Where(p => p.GetValue(userModel) is string) 
                 .All(p => string.IsNullOrWhiteSpace((p.GetValue(userModel) as string)));
        }
    }
}

OrderManager/OrderManager/Views/Shared/UserFrame.cshtml
@model UserViewModel

<div class="card card-outline-primary m-1 p-1">
    <div class="p-1" style="height:60px;width:100%; background-color:grey">
        <form id="form" asp-action="EditUser" asp-controller="User" method="post">
            <input type="hidden" asp-for="Id" />
            <font size="6">Użytkownik: @Model.FullName</font>
            <div style="float:right">
                <input class="btn btn-primary" type="submit" value="Edytuj" />
            </div>
        </form>
    </div>
</div>

OrderManager/OrderManager/Views/Shared/_AdminLayout.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="~/lib/bootstrap/css/bootstrap.css"
          asp-href-exclude="~/lib/bootstrap/css/bootstrap-grid.css" />
    <link href="~/lib/css/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid" style="margin:10px">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand">Order Manager</a>
            <a class="navbar-brand" asp-controller="AdminOrders" asp-action="NewOrders">Zamówienia</a>
            <a class="navbar-brand" asp-controller="User" asp-action="Index">Użytkownicy</a>
            <a class="navbar-brand" asp-controller="Buildings" asp-action="Index">Budowy</a>
        </nav>
        <div class="row" style="height:50px; background-color:darkorange">
            <h3 style="margin:10px">
                @ViewBag.Tittle
            </h3>
        </div>
        <div class="row">
            <div class="col">
                <div class="sidenav col-2">
                    <a asp-controller="AdminOrders" asp-action="NewOrders">Nowe</a>
                    <a asp-controller="AdminOrders" asp-action="OrdersInProgress">W trakcie realizacji</a>
                    <a asp-controller="AdminOrders" asp-action="EndedOrders">Zrealizowane</a>
                </div>
            </div>
        <div class="col-9">
         @RenderBody()
        </div>
        </div>
</body>
</html>

OrderManager/OrderManager/Views/Shared/_AdminOrdersLayout.cshtml
@{
    Layout = "_AdminLayout";
}

    <body>
        @await Component.InvokeAsync("BuildingFilter")
        @RenderBody()
    </body>